apiVersion: v1
kind: Secret
metadata:
  name: metrics-app-secret
  labels:
    app.kubernetes.io/name: {{ include "metrics-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  PASSWORD: {{ get (get .Values "env") "password" | default "changeme" | quote }}
